# Настройки
# (общий файл для ./fb2fix.sh и пакета tts-scripts)

# 1. Редактор для работы с дискретными скриптами. Возможные значения: vim, nvim (для vim и neovim соответственно)

#editor = vim
 editor = nvim

# 2. Коррекция ширины вывода текста превью в дискретных скриптах
# Использовать, если вывод "не попадает по ширине". Возможные значения: положительные и отрицательные целые числа

termcorrection = -1

# 3. Для использования ruaccent используем виртуальное окружение .venvra в рабочей директории скриптов
# Окружение делаем любым способом, например, с помощью uv. Для системноего окружения python выставить 0

usevenvra = 1

# 4. Для использования silero-stress используем виртуальное окружение .venvsi в рабочей директории скриптов
# Окружение делаем любым способом, например, с помощью uv. Для системноего окружения python выставить 0

usevenvsi = 1

